### ISSUE TITLE
Nixvim suggestion

### ISSUE THREAD

**Issue by GaetanLepage** [ZainKergaye/nixosdotfiles#1]
Hey,
I just wanted to tell you about the [clipboard.providers](https://nix-community.github.io/nixvim/clipboard/providers/index.html) option.

Setting `clipboard.providers.wl-copy.enable` will automatically install `pkgs.wl-clipboard` for you.

**Comment by ZainKergaye** [comment]
Something like that? I just rebuilt my home and should've done that before committing but I got this issue: 

`clipboard: No provider. Try :checkhealth or :h clipboard`

Adding that package in manually fixes the issue

**Comment by GaetanLepage** [comment]
The `clipboard` option is top-level, it should not be under `opts`.

**Comment by ZainKergaye** [comment]
![image](https://github.com/user-attachments/assets/bdde01ab-3b17-445f-8cd4-b752235cfc0c)
![image](https://github.com/user-attachments/assets/0a30df52-d144-437f-9983-58d2a47e7b3c)

I might be doing something wrong, is this the right way to go about it?

**Comment by ZainKergaye** [comment]
Nevermind I forgot to add `providers`
